### ISSUE TITLE
cancel_timeout in psip_trans should be greater than timer_d

### ISSUE THREAD

**Issue by MikhailKalashnikov** [poroh/psip#3]
cancel_timeout in psip_trans should be greater than timer_d.
Now it is the same (32 seconds) and cancel_timeout occurs before timer_d, before transaction terminated normally.
As a result if A party cancels a call then you will have warning in the log
`warning - trans: remote side did not respond after CANCEL request: terminate`

I suggest to set timeout to 33 seconds here https://github.com/poroh/psip/blob/master/src/psip_trans.erl#L268

**Comment by poroh** [comment]
Thank you for reporting this.

Cancel timeout is required to prevent leak of client invite transaction if it does not receive final response. I think that we can just ignore cancel_timeout info if we have already received final response.
